#ifndef GFX_SCREEN_CONFIG_H
#define GFX_SCREEN_CONFIG_H

#ifdef WINDOW_WIDTH
#define DESIRED_SCREEN_WIDTH WINDOW_WIDTH
#else
#define DESIRED_SCREEN_WIDTH 640
#endif

#ifdef WINDOW_HEIGHT
#define DESIRED_SCREEN_HEIGHT WINDOW_HEIGHT
#else
#define DESIRED_SCREEN_HEIGHT 480
#endif
#endif
